"""Atlas metadata export for Love2D."""

import json
from typing import List, Dict, Any
from .packer import SpriteRect


class AtlasExporter:
    """Exports spritesheet atlas metadata."""
    
    @staticmethod
    def export_lua(rects: List[SpriteRect], sheet_path: str) -> str:
        """Export atlas as Lua table for Love2D.
        
        Args:
            rects: List of sprite rectangles with positions
            sheet_path: Relative path to the spritesheet image
            
        Returns:
            Lua table string
        """
        lines = [
            "-- Spritesheet atlas generated by sprite-generator",
            "-- Usage: local atlas = require('path.to.this.file')",
            "",
            "return {",
            f"  sheet = '{sheet_path}',",
            "  sprites = {",
        ]
        
        for rect in rects:
            lines.append(
                f"    ['{rect.name}'] = {{"
                f"x = {rect.x}, y = {rect.y}, "
                f"w = {rect.width}, h = {rect.height}"
                f"}},"
            )
        
        lines.append("  }")
        lines.append("}")
        lines.append("")
        
        return "\n".join(lines)
    
    @staticmethod
    def export_json(rects: List[SpriteRect], sheet_path: str) -> str:
        """Export atlas as JSON.
        
        Args:
            rects: List of sprite rectangles with positions
            sheet_path: Relative path to the spritesheet image
            
        Returns:
            JSON string
        """
        data = {
            "sheet": sheet_path,
            "sprites": {}
        }
        
        for rect in rects:
            data["sprites"][rect.name] = {
                "x": rect.x,
                "y": rect.y,
                "w": rect.width,
                "h": rect.height
            }
        
        return json.dumps(data, indent=2)
    
    @staticmethod
    def export_love_quads(rects: List[SpriteRect], sheet_width: int, sheet_height: int) -> str:
        """Export as Love2D quad creation code.
        
        Args:
            rects: List of sprite rectangles
            sheet_width: Width of spritesheet
            sheet_height: Height of spritesheet
            
        Returns:
            Lua code to create quads
        """
        lines = [
            "-- Love2D Quad creation code",
            "-- Usage: Run this after loading the spritesheet image",
            "",
            "local quads = {}",
            f"local sheetWidth, sheetHeight = {sheet_width}, {sheet_height}",
            "",
        ]
        
        for rect in rects:
            lines.append(
                f"quads['{rect.name}'] = love.graphics.newQuad("
                f"{rect.x}, {rect.y}, {rect.width}, {rect.height}, "
                f"sheetWidth, sheetHeight)"
            )
        
        lines.append("")
        lines.append("return quads")
        lines.append("")
        
        return "\n".join(lines)
